import type { ReferenceEntry } from "@/types/site";

export const referenceEntries: ReferenceEntry[] = [
  {
    id: "hillside",
    name: "Hillside Su Hotel",
    logo: "/references/hotel-su.png",
    logoAlt: "Hotel SU",
    logoWide: true,
    logoScale: 1.4,
  },
  {
    id: "adam-eve",
    name: "Adam & Eve Hotel",
    logo: "/references/adam-eve.png",
    logoScale: 1.25,
  },
  {
    id: "ritz-carlton",
    name: "The Ritz-Carlton Hotel",
    logo: "/references/ritz-carlton.png",
    logoAlt: "The Ritz-Carlton",
  },
  {
    id: "w-hotel",
    name: "W Hotel",
    logo: "/references/w-hotel.png",
    logoAlt: "W Istanbul",
    logoScale: 1.3,
  },
  {
    id: "rixos",
    name: "Rixos Pera ve Elysium Otelleri",
    logo: "/references/rixos.png",
    logoAlt: "Rixos Hotels",
    logoWide: true,
    logoScale: 1.4,
  },
  {
    id: "duble-meze",
    name: "Duble Meze Bar Pera, Celal",
    logo: "/references/duble-meze.png",
    logoAlt: "Duble Meze Pera",
    logoWide: true,
    logoScale: 1.4,
  },
  {
    id: "cevahir",
    name: "Biz Cevahir Hotel",
    logo: "/references/cevahir.png",
    logoAlt: "Biz Hotel",
    logoWide: true,
    logoScale: 1.5,
  },
  {
    id: "nusret",
    name: "Nusr-Et Steakhouse",
    logo: "/references/nusret.png",
    logoScale: 1.35,
  },
  {
    id: "elexus",
    name: "Elexus Hotel",
    logo: "/references/elexus.png",
    logoAlt: "Elexus Hotel Resort Spa Girne",
    logoScale: 1.3,
  },
  {
    id: "km-hilton",
    name: "Kahramanmaraş Hilton Hotel",
    logo: "/references/kahramanmaras-hilton.png",
    logoAlt: "Hampton by Hilton Kahramanmaraş",
    logoScale: 1.25,
  },
  {
    id: "arts-hotel",
    name: "Arts Hotel",
    logo: "/references/arts-hotel.png",
    logoWide: true,
    logoScale: 1.45,
  },
  {
    id: "mavi-beyaz",
    name: "Mavi Beyaz Restaurant",
    logo: "/references/mavi-beyaz.png",
    logoWide: true,
    logoScale: 1.4,
  },
  {
    id: "cephanelik",
    name: "Cephanelik Hotel",
    logo: "/references/cephanelik.png",
    logoAlt: "Mahalle Cephanelik",
    logoScale: 1.35,
  },
  {
    id: "borovi",
    name: "Borovi Hotel",
    logo: "/references/borovi.png",
    logoAlt: "Borovi Forest Resort",
  },
  {
    id: "windsor",
    name: "Windsor Hotel",
    logo: "/references/windsor.png",
    logoAlt: "Windsor Hotel & Convention Center Istanbul",
    logoWide: true,
    logoScale: 1.6,
  },
  {
    id: "qoala",
    name: "Qoala Beach Rest",
    logo: "/references/qoala-beach.png",
    logoAlt: "Qoala Beach Club",
    logoWide: true,
    logoScale: 1.55,
  },
  {
    id: "zihni",
    name: "Zihni Bar Restaurant",
    logo: "/references/zihni.png",
    logoAlt: "Zihni Pub",
    logoWide: true,
    logoScale: 1.5,
  },
  {
    id: "anadolu-isi",
    name: "Anadolu İşi Restaurant",
    logo: "/references/antakya-isi.png",
    logoAlt: "Antakya İşi",
    logoScale: 1.35,
  },
  {
    id: "beykoz-molo",
    name: "Beykoz Molo Rest",
    logo: "/references/mola-restoran.png",
    logoAlt: "Mola Restoran",
    logoScale: 1.3,
  },
  {
    id: "balkabagi-misket",
    name: "Balkabağı Misket · Misket Hotel",
    logo: "/references/balkabagi-misket.png",
    logoAlt: "Balkabağı Misket, Misket Hotel Bodrum",
    logoScale: 1.35,
  },
];
